services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pagueveloz-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "Challenge_PagueVeloz123!"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Challenge_PagueVeloz123!' -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: src/TransactionProcessor.Api/Dockerfile
    container_name: pagueveloz-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=PagueVelozChallenge;User Id=sa;Password=Challenge_PagueVeloz123!;TrustServerCertificate=True;Encrypt=False;"
    ports:
      - "8080:8080"
